# Generated by Django 5.1.3 on 2024-11-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('logo', models.ImageField(upload_to='media/payment_method_logo')),
                ('qr', models.ImageField(upload_to='media/payment_method_qr')),
                ('person_account', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='HotelPaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=40)),
                ('payment_check', models.FileField(upload_to='media/payment_check')),
                ('status', models.CharField(choices=[('in_progress', 'В обработке'), ('denied', 'Отклонино'), ('accepted', 'Принято')], default='in_progress', max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('hotel_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hotelroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на оплату Номера',
                'verbose_name_plural': 'Заявки на оплату Намеров',
            },
        ),
    ]
