# Generated by Django 5.1.3 on 2024-11-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориии',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room_hotel', models.PositiveSmallIntegerField(verbose_name='число номера')),
                ('number_bets', models.PositiveSmallIntegerField(verbose_name='число краватей')),
                ('number_withdrawals', models.PositiveSmallIntegerField(verbose_name='число ванн')),
                ('cover', models.ImageField(upload_to='media/hotel_cover', verbose_name='иконка')),
                ('photo_hotel_room', models.ImageField(upload_to='media/photo_hotel_room', verbose_name='фото номкра')),
                ('description', models.TextField(verbose_name='описание')),
                ('prise', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('number_room', models.PositiveSmallIntegerField(verbose_name='число комнат')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Намера',
            },
        ),
    ]
