# Generated by Django 5.1.3 on 2024-11-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориии',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('smol_description', models.CharField(max_length=200, verbose_name='краткое описвнме')),
                ('description', models.TextField(verbose_name='полное описание')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room_hotel', models.PositiveSmallIntegerField(verbose_name='число номера')),
                ('number_bets', models.PositiveSmallIntegerField(verbose_name='число краватей')),
                ('number_withdrawals', models.PositiveSmallIntegerField(verbose_name='число ванн')),
                ('cover', models.ImageField(upload_to='media/hotel_cover', verbose_name='иконка')),
                ('description', models.TextField(verbose_name='описание')),
                ('prise', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('number_room', models.PositiveSmallIntegerField(verbose_name='число комнат')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Свободен'), (2, 'Занят')])),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Намера',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photo_hotel_room', verbose_name='фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.hotelroom', verbose_name='фото номера')),
            ],
        ),
    ]
