# Generated by Django 5.1.3 on 2024-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='cover',
            field=models.ImageField(default=1, upload_to='media/photo_hotel_room', verbose_name='икрнка'),
            preserve_default=False,
        ),
    ]
