# Generated by Django 5.1.3 on 2024-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Свободен'), (2, 'Занят')], default=1),
            preserve_default=False,
        ),
    ]
