# Generated by Django 5.1.3 on 2024-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_services_options_hotelroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='smol_description',
            field=models.CharField(default=1, max_length=200, verbose_name='краткое описвнме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='полное описание'),
        ),
    ]
