# Generated by Django 5.1.3 on 2024-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('tour', models.CharField(max_length=90)),
                ('payment_method', models.CharField(max_length=40)),
                ('payment_check', models.FileField(upload_to='media/payment_check')),
                ('status', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Принятая заявка на оплату Тура',
                'verbose_name_plural': 'Принятые заявки на оплату Тура',
            },
        ),
    ]
