# Generated by Django 5.1.3 on 2024-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_tour_crm_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='category',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
