# Generated by Django 5.1.3 on 2024-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(max_length=223, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=223, null=True, verbose_name='Фамилия')),
                ('phon_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('statys', models.PositiveSmallIntegerField(choices=[(1, 'Обычный Пользователь'), (2, 'Менежер'), (3, 'Бугалтер')], default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
